Repository FragSoc/esports-bot, pull requests merged in 2021-08, with the labels that each got.

#148 Fix/proper cog modularity
  README.md
  secrets.template
  src/esportsbot/DiscordReactableMenus/EmojiHandler.py
  src/esportsbot/DiscordReactableMenus/EventReactMenu.py
  src/esportsbot/DiscordReactableMenus/ExampleMenus.py
  src/esportsbot/DiscordReactableMenus/PingableMenus.py
  src/esportsbot/DiscordReactableMenus/ReactableMenu.py
  src/esportsbot/DiscordReactableMenus/__init__.py
  src/esportsbot/DiscordReactableMenus/reactable_lib.py
  src/esportsbot/base_functions.py
  src/esportsbot/bot.py
  src/esportsbot/cogs/AdminCog.py
  src/esportsbot/cogs/DefaultRoleCog.py
  src/esportsbot/cogs/EventCategoriesCog.py
  src/esportsbot/cogs/LogChannelCog.py
  src/esportsbot/cogs/MenusCog.py
  src/esportsbot/cogs/MusicCog.py
  src/esportsbot/cogs/PingableRolesCog.py
  src/esportsbot/cogs/PingablesCog.py
  src/esportsbot/cogs/RoleReactCog.py
  src/esportsbot/cogs/TwitterCog.py
  src/esportsbot/cogs/VoicemasterCog.py
  src/esportsbot/cogs/VotingCog.py
  src/esportsbot/db_gateway.py
  src/esportsbot/lib/__init__.py
  src/esportsbot/lib/client.py
  src/esportsbot/lib/discordUtil.py
  src/esportsbot/lib/stringTyping.py
  src/esportsbot/models.py
  src/esportsbot/reactionMenus/reactionMenu.py
  src/esportsbot/reactionMenus/reactionMenuDB.py
  src/esportsbot/reactionMenus/reactionPollMenu.py
  src/esportsbot/reactionMenus/reactionRoleMenu.py
  src/esportsbot/user_strings.toml
Labels: enhancement

#152 Env var cleanup
  .env
  .gitignore
  docker-compose.yml
Labels: bug, enhancement

#153 Move from `send_to_log_channel` to `client.adminLog`
  src/esportsbot/base_functions.py
  src/esportsbot/cogs/AdminCog.py
  src/esportsbot/cogs/DefaultRoleCog.py
  src/esportsbot/cogs/LogChannelCog.py
  src/esportsbot/cogs/VoicemasterCog.py
Labels: enhancement

#140 Implemented posting Twitch Live notifications to Discord Channels
  README.md
  docker-compose.yml
  src/esportsbot/cogs/TwitchCog.py
  src/esportsbot/lib/discordUtil.py
  src/esportsbot/lib/stringTyping.py
  src/esportsbot/models.py
  src/esportsbot/user_strings.toml
  src/requirements.txt
Labels: enhancement

#167 Fix incorrect error causing quotes catching to fail silently
  src/esportsbot/cogs/PingableRolesCog.py
  src/esportsbot/cogs/RoleReactCog.py
Labels: bug

#173 Group music commands together
  README.md
  src/esportsbot/cogs/MusicCog.py
Labels: enhancement, question

#177 Add `version` command
  .gitignore
  src/esportsbot/cogs/AdminCog.py
  src/esportsbot/user_strings.toml
Labels: documentation, enhancement

#179 Cleanup README formatting
  README.md
Labels: documentation, smells

#181 Fixed all messages being deleted
  src/esportsbot/cogs/MusicCog.py
Labels: bug

#151 Moved changes from old develop format to the new one
  README.md
  src/esportsbot/cogs/DefaultRoleCog.py
  src/esportsbot/models.py
  src/esportsbot/user_strings.toml
Labels: enhancement

#183 Hotfixes from Testing Session
  README.md
  src/esportsbot/cogs/DefaultRoleCog.py
  src/esportsbot/cogs/EventCategoriesCog.py
  src/esportsbot/cogs/MusicCog.py
  src/esportsbot/cogs/VoicemasterCog.py
Labels: bug

#187 Custom help command implementation
  README.md
  src/esportsbot/cogs/AdminCog.py
  src/esportsbot/cogs/DefaultRoleCog.py
  src/esportsbot/cogs/EventCategoriesCog.py
  src/esportsbot/cogs/MusicCog.py
  src/esportsbot/cogs/PingableRolesCog.py
  src/esportsbot/cogs/RoleReactCog.py
  src/esportsbot/cogs/TwitchCog.py
  src/esportsbot/cogs/TwitterCog.py
  src/esportsbot/cogs/VoicemasterCog.py
  src/esportsbot/cogs/VotingCog.py
  src/esportsbot/lib/CustomHelpCommand.py
  src/esportsbot/lib/client.py
  src/esportsbot/user_strings.toml
Labels: enhancement
