Repository FragSoc/esports-bot, pull requests merged in 2021-06, with the labels that each got.

#90 Remove `todo` file
  todo
Labels: bug, documentation

#67 Fixed some bugs and made some enhancements in the MusicCog
  src/esportsbot/bot.py
  src/esportsbot/cogs/MusicCog.py
  src/esportsbot/lib/client.py
  src/esportsbot/user_strings.toml
Labels: bug, enhancement

#74 Add yapf style file
  .gitattributes
  setup.cfg
Labels: documentation, enhancement, question

#125 Several pingme and role menu bug fixes
  src/esportsbot/cogs/EventCategoriesCog.py
  src/esportsbot/cogs/MenusCog.py
  src/esportsbot/cogs/PingablesCog.py
  src/esportsbot/lib/client.py
  src/esportsbot/reactionMenus/reactionMenu.py
  src/esportsbot/reactionMenus/reactionPollMenu.py
Labels: bug

#133 Fixed bugs relating to MusicCog
  src/esportsbot/bot.py
  src/esportsbot/cogs/AdminCog.py
  src/esportsbot/cogs/MusicCog.py
Labels: bug

#91 Minimum versions in README
  Dockerfile
  README.md
  docker-compose.yml
Labels: documentation

#84 Add user strings to voice master cog
  src/esportsbot/cogs/VoicemasterCog.py
  src/esportsbot/user_strings.toml
Labels: enhancement

#81 Add strIsUserMention and strIsChannelMention functions
  src/esportsbot/lib/stringTyping.py
Labels: bug, enhancement

#139 Migration to SQLAlchemy for DB communication
  .gitignore
  README.md
  docker-compose.yml
  src/esportsbot/base_functions.py
  src/esportsbot/bot.py
  src/esportsbot/cogs/AdminCog.py
  src/esportsbot/cogs/DefaultRoleCog.py
  src/esportsbot/cogs/EventCategoriesCog.py
  src/esportsbot/cogs/LogChannelCog.py
  src/esportsbot/cogs/MenusCog.py
  src/esportsbot/cogs/MusicCog.py
  src/esportsbot/cogs/PingablesCog.py
  src/esportsbot/cogs/TwitchIntegrationCog.py
  src/esportsbot/cogs/TwitterIntegrationCog.py
  src/esportsbot/cogs/VoicemasterCog.py
  src/esportsbot/db_gateway.py
  src/esportsbot/generate_schema.py
  src/esportsbot/lib/client.py
  src/esportsbot/models.py
  src/esportsbot/reactionMenus/reactionMenu.py
  src/esportsbot/reactionMenus/reactionMenuDB.py
  src/esportsbot/reactionMenus/reactionPollMenu.py
  src/esportsbot/reactionMenus/reactionRoleMenu.py
  src/requirements.txt
Labels: enhancement

#135 README Standardisation
  .gitignore
  README.md
  secrets.template
  src/esportsbot/lib/client.py
Labels: documentation, enhancement
