Repository FragSoc/esports-bot, pull requests merged in 2021-09, with the labels that each got.

#189 Remove `.env` symlink that didn't work on all systems
  .env
  docker-compose.yml
Labels: bug

#194 Command to easily set Game Rep permissions
  README.md
  src/esportsbot/cogs/AdminCog.py
  src/esportsbot/user_strings.toml
Labels: enhancement

#195 Standardised and cleaned up codebase
  src/esportsbot/DiscordReactableMenus/EmojiHandler.py
  src/esportsbot/DiscordReactableMenus/EventReactMenu.py
  src/esportsbot/DiscordReactableMenus/ExampleMenus.py
  src/esportsbot/DiscordReactableMenus/PingableMenus.py
  src/esportsbot/DiscordReactableMenus/ReactableMenu.py
  src/esportsbot/DiscordReactableMenus/reactable_lib.py
  src/esportsbot/base_functions.py
  src/esportsbot/bot.py
  src/esportsbot/cogs/AdminCog.py
  src/esportsbot/cogs/DefaultRoleCog.py
  src/esportsbot/cogs/EventCategoriesCog.py
  src/esportsbot/cogs/LogChannelCog.py
  src/esportsbot/cogs/MusicCog.py
  src/esportsbot/cogs/PingableRolesCog.py
  src/esportsbot/cogs/RoleReactCog.py
  src/esportsbot/cogs/TwitchCog.py
  src/esportsbot/cogs/TwitterCog.py
  src/esportsbot/cogs/VoicemasterCog.py
  src/esportsbot/cogs/VotingCog.py
  src/esportsbot/db_gateway.py
  src/esportsbot/lib/CustomHelpCommand.py
  src/esportsbot/lib/__init__.py
  src/esportsbot/lib/client.py
  src/esportsbot/lib/discordUtil.py
  src/esportsbot/lib/emotes.py
  src/esportsbot/lib/exceptions.py
  src/esportsbot/lib/stringTyping.py
  src/esportsbot/lib/timeUtil.py
  src/esportsbot/models.py
Labels: documentation, enhancement

#197 Fixed issues raised during user testing for pingme roles
  src/esportsbot/cogs/PingableRolesCog.py
Labels: enhancement

#198 Changed the signature of the admin_log function
  src/esportsbot/bot.py
  src/esportsbot/cogs/AdminCog.py
  src/esportsbot/cogs/DefaultRoleCog.py
  src/esportsbot/cogs/LogChannelCog.py
  src/esportsbot/cogs/VoicemasterCog.py
  src/esportsbot/lib/client.py
  src/esportsbot/user_strings.toml
Labels: enhancement

#199 Merge from Dev to Master for version 1.1
  .gitattributes
  .gitignore
  Dockerfile
  README.md
  docker-compose.yml
  secrets.template
  setup.cfg
  src/esportsbot/DiscordReactableMenus/EmojiHandler.py
  src/esportsbot/DiscordReactableMenus/EventReactMenu.py
  src/esportsbot/DiscordReactableMenus/ExampleMenus.py
  src/esportsbot/DiscordReactableMenus/PingableMenus.py
  src/esportsbot/DiscordReactableMenus/ReactableMenu.py
  src/esportsbot/DiscordReactableMenus/__init__.py
  src/esportsbot/DiscordReactableMenus/reactable_lib.py
  src/esportsbot/base_functions.py
  src/esportsbot/bot.py
  src/esportsbot/cogs/AdminCog.py
  src/esportsbot/cogs/DefaultRoleCog.py
  src/esportsbot/cogs/EventCategoriesCog.py
  src/esportsbot/cogs/LogChannelCog.py
  src/esportsbot/cogs/MenusCog.py
  src/esportsbot/cogs/MusicCog.py
  src/esportsbot/cogs/PingableRolesCog.py
  src/esportsbot/cogs/PingablesCog.py
  src/esportsbot/cogs/RoleReactCog.py
  src/esportsbot/cogs/TwitchCog.py
  src/esportsbot/cogs/TwitchIntegrationCog.py
  src/esportsbot/cogs/TwitterCog.py
  src/esportsbot/cogs/TwitterIntegrationCog.py
  src/esportsbot/cogs/VoicemasterCog.py
  src/esportsbot/cogs/VotingCog.py
  src/esportsbot/db_gateway.py
  src/esportsbot/generate_schema.py
  src/esportsbot/lib/CustomHelpCommand.py
  src/esportsbot/lib/__init__.py
  src/esportsbot/lib/client.py
  src/esportsbot/lib/discordUtil.py
  src/esportsbot/lib/emotes.py
  src/esportsbot/lib/exceptions.py
  src/esportsbot/lib/stringTyping.py
  src/esportsbot/lib/timeUtil.py
  src/esportsbot/models.py
  src/esportsbot/reactionMenus/reactionMenu.py
  src/esportsbot/reactionMenus/reactionMenuDB.py
  src/esportsbot/reactionMenus/reactionPollMenu.py
  src/esportsbot/reactionMenus/reactionRoleMenu.py
  src/esportsbot/user_strings.toml
  src/main.py
  src/requirements.txt
Labels: documentation, enhancement
